const db=supabase.createClient(window.SUPABASE_URL,window.SUPABASE_PUBLISHABLE_KEY);let session=null;const $=id=>document.getElementById(id);const money=n=>n?new Intl.NumberFormat('fa-IR').format(n)+' تومان':'—';
async function isAdmin(){const {data:{user}}=await db.auth.getUser();if(!user)return false;const {data,error}=await db.rpc('is_admin');return !error&&data===true}async function boot(){const {data}=await db.auth.getSession();if(data.session){session=data.session;if(await isAdmin())showDash();else await db.auth.signOut()} }function showDash(){$('loginBox').classList.add('hidden');$('dashboard').classList.remove('hidden');refresh();checkMfa()}
$('login').onclick=async()=>{const {error}=await db.auth.signInWithPassword({email:$('email').value,password:$('password').value});if(error){$('loginStatus').textContent=error.message;return}const {data:{session:s}}=await db.auth.getSession();const aal=s?.user?.aal||'aal1';if(aal!=='aal2'){const {data}=await db.auth.mfa.listFactors();const factor=data?.totp?.find(f=>f.status==='verified');if(factor){const ch=await db.auth.mfa.challenge({factorId:factor.id});const code=prompt('کد ۶ رقمی برنامه Authenticator:');const v=await db.auth.mfa.verify({factorId:factor.id,challengeId:ch.data.id,code});if(v.error){$('loginStatus').textContent='کد دومرحله‌ای نادرست است';await db.auth.signOut();return}}}if(await isAdmin())showDash();else{await db.auth.signOut();$('loginStatus').textContent='این حساب دسترسی مدیر ندارد.'}};
$('logout').onclick=async()=>{await db.auth.signOut();location.reload()};
async function refresh(){const [{count:vc},{count:pc},{count:mc}]=await Promise.all([db.from('visits').select('*',{count:'exact',head:true}),db.from('properties').select('*',{count:'exact',head:true}),db.from('support_messages').select('*',{count:'exact',head:true}).eq('read',false)]);$('visitCount').textContent=vc||0;$('propertyCount').textContent=pc||0;$('messageCount').textContent=mc||0;const {data:ps}=await db.from('properties').select('*').order('created_at',{ascending:false}).limit(50);$('adminListings').innerHTML=(ps||[]).map(p=>`<div class="admin-item"><b>${esc(p.title)}</b> — ${esc(p.code)} — ${money(p.price)}<br>${esc(p.owner_name||'')} ${esc(p.owner_phone||'')}<br><button onclick="delProp('${p.id}')">حذف</button></div>`).join('')||'ملکی ثبت نشده است';const {data:ms}=await db.from('support_messages').select('*').order('created_at',{ascending:false}).limit(50);$('messages').innerHTML=(ms||[]).map(m=>`<div class="admin-item"><b>${esc(m.name)}</b> ${esc(m.phone||'')}<br>${esc(m.message)}<br><small>${new Date(m.created_at).toLocaleString('fa-IR')}</small></div>`).join('')||'پیامی نیست'}
async function delProp(id){if(confirm('حذف شود؟')){await db.from('properties').delete().eq('id',id);refresh()}}window.delProp=delProp;function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
$('propertyForm').addEventListener('submit',async e=>{e.preventDefault();$('propertyStatus').textContent='در حال ثبت...';const f=new FormData(e.target);const payload={title:f.get('title'),type:f.get('type'),deal:f.get('deal'),area:+f.get('area')||null,price:+f.get('price')||null,location:f.get('location'),rooms:+f.get('rooms')||null,owner_name:f.get('owner_name'),owner_phone:f.get('owner_phone'),description:f.get('description'),urgent:f.has('urgent'),special:f.has('special'),ladder:f.has('ladder')};const {data:p,error}=await db.from('properties').insert(payload).select().single();if(error){$('propertyStatus').textContent=error.message;return}const files=[...f.getAll('media')].filter(x=>x.size);for(const file of files){const path=`${p.id}/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const up=await db.storage.from('property-media').upload(path,file,{contentType:file.type,upsert:false});if(!up.error)await db.from('property_media').insert({property_id:p.id,path,media_type:file.type})}$('propertyStatus').textContent='ملک ثبت شد با کد '+p.code;e.target.reset();refresh()});
async function checkMfa(){const {data}=await db.auth.mfa.listFactors();const f=data?.totp||[];$('mfaState').textContent=f.some(x=>x.status==='verified')?'۲ مرحله‌ای فعال است.':'۲ مرحله‌ای فعال نیست.'}
$('setupMfa').onclick=async()=>{const {data,error}=await db.auth.mfa.enroll({factorType:'totp',friendlyName:'Amlak Asghari Admin'});if(error){$('mfaBox').textContent=error.message;return}$('mfaBox').innerHTML=`<p>QR را با Google Authenticator یا برنامه مشابه اسکن کنید.</p><img style="max-width:220px" src="${data.totp.qr_code}"><p>اگر QR نشد: ${data.totp.secret}</p><input id="mfaCode" placeholder="کد ۶ رقمی"><button id="verifyMfa">فعال‌سازی</button>`;$('verifyMfa').onclick=async()=>{const ch=await db.auth.mfa.challenge({factorId:data.id});const v=await db.auth.mfa.verify({factorId:data.id,challengeId:ch.data.id,code:$('mfaCode').value});$('mfaBox').textContent=v.error?v.error.message:'۲ مرحله‌ای فعال شد.';checkMfa()}};
$('changePass').onclick=async()=>{const {error}=await db.auth.updateUser({password:$('newPass').value});$('securityStatus').textContent=error?error.message:'رمز عبور تغییر کرد.'};boot();
